#!/usr/bin/with-contenv bash
# shellcheck shell=bash

# Create default rsync config file
if [[ ! -f /config/rsyncd.conf ]]; then
  cat <<EOF > /config/rsyncd.conf
uid = ${USER_NAME}
gid = ${USER_NAME}
use chroot = yes
log file = /dev/stdout
reverse lookup = no
[${RSYNC_MODULE:-volume}]
    read only = false
    path = ${RSYNC_PATH:-/data}
    comment = default rsync volume
EOF
fi
